#!/usr/bin/env python
# -*- coding:utf-8 -*-
#字典的每个键值对用冒号：分割，每对之间用逗号分隔
#字典用{}包含
d = {'k1':1,'k2':2}
#访问值 变量[key]
print d['k1']
#修改或增加 变量[key] = value
d['k1'] = 10
print d['k1']
#增加
d['k3'] = 9
print d

#删除
del d['k1']
print d
#删除字典
del d
#字典特性
#1、字典的值可以是任意python对象d
d = {'k1':1,'k2':[1,2,3],'k3':{'k1':10}}
#字典的key是唯一的，且key必须是不可变的类型，可以是数字、字符串、元组，不能是列表
d = {1:10,(1,):11}
#字典是无序的，不能索引，不能切片
#内置函数、
#len
print(len(d))
#字典的方法
#1、dict.clear() 清空列表
#d.clear()
#2.fromkeys(seq,val)
l = [1,2,3,4,5,]
new_dict = dict.fromkeys(l,10)
print new_dict

#dict.get('key',default) 获取key的值,如果key不存在则返回default的值

print d.get(5,6)

#in
if 'k1' in d:
    print 'd'

    #dict.itmes(),以列表的形势返回可遍历的元组数组
for item in d.items():
    print (item)
#dict.keys(),返回key数组
#dict.values()
for value in d.values():
    print (value)
    print (d.values)
#dict.update(d2),把d2的键值对更新到d1中
d.update(d1)

